import time


dict_of_keys = {"c_yes" : ['CMaj7', 'Dmin7', 'Emin7', 'FMaj7', 'G7', 'Amin7', 'Bdim7'],
                "c_no" : ['CMaj', 'Dmin', 'Emin', 'FMaj', 'GMaj', 'Amin', 'Bdim'],
                "d_yes" : ['DMaj7', 'Emin7', 'F#min7', 'G7', 'A7', 'Bmin7', 'C#dim7'],
                "d_no" : ['DMaj', 'Emin', 'F#min', 'GMaj', 'AMaj', 'Bmin', 'C#dim'],
                "e_yes" : ['EMaj7', 'F#min7', 'G#min7', 'AMaj7', 'B7', 'C#min7', 'D#dim7'],
                "e_no" : ['EMaj', 'F#min', 'G#min', 'AMaj', 'BMaj', 'C#min', 'D#dim'],
                "f_yes" : ['FMaj7', 'Gmin7', 'Amin7', 'BbMaj7', 'C7', 'Dmin7', 'Edim7'],
                "f_no" : ['FMaj', 'Gmin', 'Amin', 'BbMaj', 'CMaj', 'Dmin', 'Edim'],
                "g_yes" : ['GMaj7', 'Amin7', 'Bmin7', 'CMaj7', 'D7', 'Emin7', 'F#dim7'],
                "g_no" : ['GMaj', 'Amin', 'Bmin', 'CMaj', 'DMaj', 'Emin', 'F#dim'],
                "a_yes" : ['AMaj7', 'Bmin7', 'C#min7', 'DMaj7', 'E7', 'F#min7', 'G#dim7'],
                "a_no" : ['AMaj', 'Bmin', 'C#min', 'DMaj', 'EMaj', 'F#min', 'G#dim'],
                "b_yes" : ['BMaj7', 'C#min7', 'D#min7', 'EMaj7', 'F#7', 'G#min7', 'A#dim7'],
                "b_no" : ['BMaj', 'C#min', 'D#min', 'EMaj', 'F#Maj', 'G#min', 'A#dim'],
                "db_yes" : ['DbMaj7', 'Ebmin7', 'Fmin7', 'GbMaj7', 'Ab7', 'Bbmin7', 'Cdim7'],
                "db_no" : ['DbMaj', 'Ebmin', 'Fmin', 'GbMaj', 'AbMaj', 'Bbmin', 'Cdim'],
                "eb_yes" : ['EbMaj7', 'Fmin7', 'Gmin7', 'AbMaj7', 'Bb7', 'Cmin7', 'Ddim7'],
                "eb_no" : ['EbMaj', 'Fmin', 'Gmin', 'AbMaj', 'BbMaj', 'Cmin', 'Ddim'],
                "gb_yes" : ['GbMaj7', 'Abmin7', 'Bbmin7', 'CbMaj7', 'Bb7', 'Ebmin7', 'Fdim7'],
                "gb_no" : ['GbMaj', 'Abmin', 'Bbmin', 'CbMaj', 'Bb', 'Ebmin', 'Fdim'],
                "ab_yes" : ['AbMaj7', 'Bbmin7', 'Cmin7', 'DbMaj7', 'Eb7', 'Fmin7', 'Gdim7'],
                "ab_no" : ['AbMaj', 'Bbmin', 'Cmin', 'DbMaj', 'Eb', 'Fmin', 'Gdim'],
                "bb_yes" : ['BbMaj7', 'Cmin7', 'Dmin7', 'EbMaj7', 'F7', 'Gmin7', 'Adim7'],
                "bb_no" : ['BbMaj', 'Cmin', 'Dmin', 'EbMaj', 'FMaj', 'Gmin', 'Adim']}


while True:
        # REQUEST
        # opens the text file generated by the main program and stores the user's key
        infile = open('client_key.txt', 'r')
        user_key = infile.read()
        infile.close()

        # copies the appropriate list of chords from the user-selected key
        list_of_chords = dict_of_keys[user_key]

        # writes the list of chords to a new text file for the main program to use
        outfile = open('server_key.txt', 'w')
        #outfile.seek(0)
        #outfile.truncate()
        outfile.write(str(list_of_chords))
        outfile.close()
